export const DRAFT_RANK_MAP: Record<string, string> = {
  "Xauli": "01",
  "Iker": "02",
  "Celita Líder Trek": "03",
  "King Remco": "04",
  "Javito's Cojostars": "05",
  "diegocruga": "06",
  "JF": "07",
  "Madafaca": "08",
  "Adrián M.": "09",
  "Xemita el cagalera": "10",
  "Pantic": "11",
  "carloscampas": "12",
  "Salva CSS": "13",
  "K": "14",
  "RedBluff IsraelHP": "15",
  "monty team": "16",
  "IbaiWRT": "17",
  "Osintron Fachafranco": "18",
  "Colotto": "19",
  "Iñaki ML": "20",
  "Chukipanda": "21",
  "The Notorious O.R.G": "22",
  "Panetta Cycling Team": "23",
  "Manfredi CT": "24",
};
