import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import fetch from "node-fetch";
import { GoogleGenAI } from "@google/genai";
import * as cheerio from "cheerio";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Enable JSON request body parsing
  app.use(express.json({ limit: "5mb" }));

  // AI narrative generation endpoint
  app.post("/api/generate-narrative", async (req, res) => {
    const { raceName, teamsData, stagesData, retiredData, streaksAndStatsData, draftPicksData } = req.body;
    
    if (!raceName) {
      return res.status(400).json({ error: "Missing required 'raceName' parameter" });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(400).json({ 
        error: "GEMINI_API_KEY no está configurado en las variables de entorno del servidor. Por favor, añádelo en Settings > Secrets en AI Studio para disfrutar del resumen narrativo automático por IA." 
      });
    }

    try {
      console.log(`[AI Narrative] Generating summary for race: ${raceName}`);
      
      const ai = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build"
          }
        }
      });

      const promptString = `Redacta una crónica periodística deportiva de ciclismo muy emocionante, completa, analítica y profesional en español para la carrera "${raceName}".

Aquí tienes los datos reales de la carrera del juego fantasy para que los analices estructuradamente con lujo de detalle:

1. CLASIFICACIÓN DE EQUIPOS (Márgenes de puntos y posiciones):
${JSON.stringify(teamsData, null, 2)}

2. DESGLOSE DE ETAPAS / CLASIFICACIONES CLAVE (Rendimiento destacado):
${JSON.stringify(stagesData, null, 2)}

3. ESTADÍSTICAS AVANZADAS Y RACHAS DE MANAGERS:
${JSON.stringify(streaksAndStatsData, null, 2)}

4. RENDIMIENTO DEL DRAFT (Éxitos rotundos vs. Desilusiones del presupuesto):
${JSON.stringify(draftPicksData, null, 2)}

5. CICLISTAS RETIRADOS (Abandonos dolorosos que han perjudicado a los managers):
${JSON.stringify(retiredData, null, 2)}

Instrucciones de formato e identidad:
- IMPORTANTE: En toda tu redacción, los nombres de los equipos/mánagers deben indicarse siempre exactamente en el formato "Equipo [#Orden]" (ej: El Gallo [#05]), y los ciclistas deben indicarse exactamente como "Ciclista <Ronda> (Equipo)" (ej: Tadej Pogacar <01> (El Gallo [#05])). No los abrevies ni alteres este formato en ningún sitio.
- Usa un lenguaje periodístico deportivo vibrante, ameno, ingenioso y de gran calidad literaria (estilo crónica de Marca o El País).
- Comienza con un TÍTULO llamativo e inspirador destacado en negrita o encabezado de Markdown (ej: "# Épica en las carreteras: El reinado de...").
- Organiza el artículo en secciones lógicas utilizando subtítulos en Markdown:
  - "## Batalla de managers en el Fantasy" (comenta el podio y la lucha cerrada)
  - "## Consistencia, Rachas y Sequías" (analiza detalladamente quién puntuó en todas las etapas, rachas, y quién sufre sequías de puntos según los datos facilitados)
  - "## El Mercado del Draft: Chollos y Decepciones" (menciona con nombres y apellidos a los ciclistas que fueron "chollos" tardíos y a las grandes desilusiones de rondas altas)
  - "## El Drama de los Abandonos" (destaca cómo impactaron las bajas en las filas de los mánagers)
- Destaca cómo los abandonos y las elecciones del draft impactaron las posibilidades de los mánagers.
- No inventes datos que contradigan los proporcionados. Céntrate en dar narrativa, carácter y alma a estas estadísticas detalladas para que parezca escrito por un analista técnico de primer nivel.`;

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: promptString,
        config: {
          systemInstruction: "Eres un redactor deportivo experto en ciclismo profesional, especialista en análisis estadístico y cronista oficial del Fantasy Ciclismo HLG. Redactas crónicas espectaculares, rigurosas con los datos de rachas, draft y abandonos proporcionados, pero con un estilo literario apasionante, agudo y lleno de metáforas del pelotón. Tu respuesta debe ser exclusivamente en formato Markdown."
        }
      });

      const text = response.text;
      if (!text) {
        throw new Error("No text was generated by Gemini");
      }

      res.json({ narrative: text });
    } catch (error: any) {
      console.error("[AI Narrative] Error generating narrative:", error);
      res.status(500).json({ 
        error: "Hubo un error al generar la narrativa con IA: " + (error.message || error) 
      });
    }
  });

  // Proxy endpoint for Google Sheets to bypass CORS and prevent type-casting loss
  app.get("/api/proxy-sheet", async (req, res) => {
    const sheetUrl = req.query.url as string;
    if (!sheetUrl) {
      return res.status(400).json({ error: "Missing 'url' parameter" });
    }

    try {
      console.log(`[Proxy] Fetching Sheet URL: ${sheetUrl}`);
      const response = await fetch(sheetUrl);
      if (!response.ok) {
        throw new Error(`Google Sheets responded with status ${response.status}`);
      }
      const data = await response.text();
      
      // Set appropriate content type and encoding
      res.setHeader("Content-Type", "text/csv; charset=utf-8");
      res.setHeader("Access-Control-Allow-Origin", "*");
      res.send(data);
    } catch (error: any) {
      console.error("[Proxy] Error fetching sheet:", error);
      res.status(500).json({ error: error.message || "Failed to fetch spreadsheet data" });
    }
  });

  // FirstCycling scraping endpoint to directly fetch and parse stage results
  app.post("/api/fetch-first-cycling", async (req, res) => {
    const { url } = req.body;
    if (!url) {
      return res.status(400).json({ error: "Falta el parámetro 'url'" });
    }

    try {
      console.log(`[FirstCycling Scraper] Fetching: ${url}`);
      const response = await fetch(url, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
        }
      });

      if (!response.ok) {
        throw new Error(`FirstCycling respondió con estado ${response.status}`);
      }

      const html = await response.text();
      const $ = cheerio.load(html);

      // Parse Carrera, Etapa, Tipo, Year
      let carrera = "";
      let etapa = "";
      let tipo = "Etapa";
      let year = new Date().getFullYear().toString();

      // Try to get header title from h1/h2 or title tag
      const headerTitleText = $("div.col-md-12 h1, div.col-md-12 h2, h1, h2").first().text().trim();
      const titleText = $("title").text().trim();
      const workingTitle = headerTitleText || titleText;

      if (workingTitle) {
        // Extract year
        const yearMatch = workingTitle.match(/\b(202\d)\b/);
        if (yearMatch) {
          year = yearMatch[1];
        }

        // Extract stage
        const stageMatch = workingTitle.match(/(?:Stage|Etapa)\s+(\d+)/i);
        if (stageMatch) {
          etapa = stageMatch[1];
          tipo = "Etapa";
        } else if (workingTitle.toLowerCase().includes("general classification") || workingTitle.toLowerCase().includes("final")) {
          tipo = "Clasificación final";
          etapa = "CG";
        }

        // Extract Carrera name
        carrera = workingTitle
          .replace(/\b(202\d)\b/g, "")
          .replace(/(?:Stage|Etapa|Etappe)\s+\d+/gi, "")
          .replace(/results/gi, "")
          .replace(/resultados/gi, "")
          .replace(/classification/gi, "")
          .replace(/clasificación/gi, "")
          .replace(/general/gi, "")
          .replace(/final/gi, "")
          .replace(/firstcycling(?:\.com)?/gi, "")
          .replace(/first cycling/gi, "")
          .replace(/-\s*-\s*/g, "")
          .replace(/[||\-]/g, "")
          .trim()
          .replace(/\s+/g, " ");
      }

      // Try parsing from URL parameters as override
      try {
        const urlObj = new URL(url);
        const eParam = urlObj.searchParams.get("e");
        if (eParam) {
          const numEtapa = parseInt(eParam, 10);
          if (!isNaN(numEtapa)) {
            etapa = String(numEtapa);
            tipo = "Etapa";
          } else {
            etapa = eParam.toUpperCase();
            if (etapa === "CG" || etapa === "GENERAL") {
              tipo = "Clasificación final";
            }
          }
        }
        const yParam = urlObj.searchParams.get("y");
        if (yParam && /^\d{4}$/.test(yParam)) {
          year = yParam;
        }
      } catch (e) {
        // ignore
      }

      // Clean up carrera name if empty or generic
      if (!carrera) {
        carrera = "Carrera Desconocida";
      }

      // Date extraction
      let fecha = "";
      $("p, li, div, td, span").each((i, el) => {
        if (fecha) return;
        const text = $(el).text().trim();
        const m = text.match(/(?:Date:\s*)?(\d{2})\.(\d{2})\.(\d{4})/i);
        if (m) {
          fecha = `${m[3]}-${m[2]}-${m[1]}`; // YYYY-MM-DD
        }
      });

      if (!fecha) {
        const today = new Date();
        const dd = String(today.getDate()).padStart(2, '0');
        const mm = String(today.getMonth() + 1).padStart(2, '0');
        const yyyy = today.getFullYear();
        fecha = `${yyyy}-${mm}-${dd}`;
      }

      // Format date as DD/MM/YYYY for the output string
      let outputFecha = fecha;
      if (fecha.includes("-")) {
        const parts = fecha.split("-");
        if (parts.length === 3) {
          outputFecha = `${parts[2]}/${parts[1]}/${parts[0]}`;
        }
      }

      const rows: any[] = [];
      const tabulatedLines: string[] = [];

      // Let's look at all tables and check if they contain rider links
      $("table").each((tblIdx, tblEl) => {
        const table = $(tblEl);
        
        // Determine columns indices from headers
        let uciColIdx = -1;
        let teamColIdx = -1;
        let riderColIdx = -1;
        
        table.find("th").each((hIdx, thEl) => {
          const hText = $(thEl).text().trim().toUpperCase();
          if (hText.includes("UCI")) {
            uciColIdx = hIdx;
          } else if (hText.includes("TEAM") || hText.includes("EQUIPO")) {
            teamColIdx = hIdx;
          } else if (hText.includes("RIDER") || hText.includes("CICLISTA") || hText.includes("NAME")) {
            riderColIdx = hIdx;
          }
        });

        table.find("tr").each((trIdx, trEl) => {
          const tr = $(trEl);
          const riderLink = tr.find('a[href^="rider.php?r="]');
          if (riderLink.length > 0) {
            const riderName = riderLink.text().trim();
            
            // Find team
            const teamLink = tr.find('a[href^="team.php?id="], a[href^="team.php?l="]');
            let teamName = teamLink.length > 0 ? teamLink.text().trim() : "";
            
            // Pos (usually first column)
            const firstTd = tr.find("td, th").first();
            const pos = firstTd.text().trim();

            // Validate pos: must be numeric or a standard retired code
            const isRetired = ["DNF", "DNS", "OTL", "DSQ", "OOT"].includes(pos.toUpperCase());
            const isValidPos = /^\d+$/.test(pos) || isRetired;

            if (isValidPos && riderName) {
              let uciPoints = "";
              const tds = tr.find("td");

              // If we have UCI column index, try to get from that exact column
              if (uciColIdx !== -1 && uciColIdx < tds.length) {
                uciPoints = $(tds[uciColIdx]).text().trim();
              } else {
                // Fallback: look at the cells after teamLink
                let teamIdx = -1;
                tds.each((cIdx, tdEl) => {
                  if ($(tdEl).find('a[href^="team.php?id="], a[href^="team.php?l="]').length > 0) {
                    teamIdx = cIdx;
                  }
                });

                if (teamIdx !== -1) {
                  for (let cIdx = teamIdx + 1; cIdx < tds.length; cIdx++) {
                    const val = $(tds[cIdx]).text().trim();
                    if (/^\d+(\.\d+)?$/.test(val)) {
                      uciPoints = val;
                    }
                  }
                }
              }

              // Let's clean names
              const cleanRider = riderName.replace(/\s+\(.*?\)$/, '').trim();
              const cleanTeam = teamName.replace(/\s+\(.*?\)$/, '').trim();

              rows.push({
                pos,
                riderName: cleanRider,
                teamName: cleanTeam,
                uciPoints: uciPoints || ""
              });

              // Format: Fecha Carrera Tipo Etapa Pos Nacido b1 Ciclista Equipo UCI
              tabulatedLines.push(`${outputFecha}\t${carrera}\t${tipo}\t${etapa}\t${pos}\t\t\t${cleanRider}\t${cleanTeam}\t${uciPoints}`);
            }
          }
        });
      });

      res.json({
        success: true,
        carrera,
        etapa,
        tipo,
        fecha, // YYYY-MM-DD
        tabulatedData: tabulatedLines.join("\n"),
        rowsCount: rows.length
      });

    } catch (error: any) {
      console.error("[FirstCycling Scraper] Error scraping URL:", error);
      res.status(500).json({
        success: false,
        error: "Error al raspar la página de FirstCycling: " + (error.message || error)
      });
    }
  });


  // Health check endpoint
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // Vite middleware setup for development, otherwise serve static files
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
